on: push

jobs:
  test:
    runs-on: self-hosted
    name: Erlang/OTP
    strategy:
      fail-fast: false
      matrix:
        container:
          - erlang:25
          - erlang:25-alpine
          - erlang:23
          - erlang:23-alpine
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      # - name: asdf_install
      #   uses: asdf-vm/actions/install@v1
      - run: rebar3 compile
      - run: rebar3 eunit
      - run: rebar3 ct
