on: push

jobs:
  test:
    runs-on: self-hosted
    name: Erlang/OTP
    strategy:
      fail-fast: false
      matrix:
        container:
          - erlang:25
          - erlang:25-alpine
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 get-deps
      - run: rebar3 compile
      - run: rebar3 check
